package_rename_config:
  android:
    app_name: Test Apps # (String) The display name of the android app
    package_name: com.sahid.test # (String) The package name of the android app
    override_old_package: com.sahid.test # (String) The old package name of the android app
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: Test Apps # (String) The display name of the ios app
    bundle_name: Test Apps # (String) The bundle name of the ios app
    package_name: com.sahid.test # (String) The product bundle identifier of the ios app

  linux:
    app_name: Test Apps # (String) The window title of the linux app
    package_name: com.sahid.test # (String) The application id of the linux app
    exe_name: Test_Apps # (String) The executable name (binary name) of the linux app

  macos:
    app_name: Test Apps # (String) The product name of the macos app
    package_name: com.sahid.test # (String) The product bundle identifier of the macos app
    copyright_notice: Apps # (String) The product copyright of the macos app

  web:
    app_name: Test Apps # (String) The title of the web app and PWA
    short_app_name: Test Apps # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: Test Apps # (String) The description of the web app and PWA

  windows:
    app_name: Test Apps # (String) The window title & software name of the windows app
    organization: Apps # (String) The organization name (company name) of the windows app
    copyright_notice: Apps # (String) The legal copyright of the windows app
    exe_name: Test_Apps # (String) The executable name (binary name) of the windows app
