// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLjFlaAKvwTrOknno26curb_Ft4eKXBTI',
    appId: '1:984481107482:web:230016130964e8a7a44ba3',
    messagingSenderId: '984481107482',
    projectId: 'food-order-f4d07',
    authDomain: 'food-order-f4d07.firebaseapp.com',
    storageBucket: 'food-order-f4d07.firebasestorage.app',
    measurementId: 'G-Y73ENKGCS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArnqcanAotbtGlY2g9uMsryCb7QRgd2R0',
    appId: '1:984481107482:android:333c5c8cf170686da44ba3',
    messagingSenderId: '984481107482',
    projectId: 'food-order-f4d07',
    storageBucket: 'food-order-f4d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZT6lGrPEIhpK4m8BslI8lrdC5eENJDQ',
    appId: '1:984481107482:ios:e71a376f07c0225ca44ba3',
    messagingSenderId: '984481107482',
    projectId: 'food-order-f4d07',
    storageBucket: 'food-order-f4d07.firebasestorage.app',
    iosBundleId: 'com.company.opet.order',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZT6lGrPEIhpK4m8BslI8lrdC5eENJDQ',
    appId: '1:984481107482:ios:e71a376f07c0225ca44ba3',
    messagingSenderId: '984481107482',
    projectId: 'food-order-f4d07',
    storageBucket: 'food-order-f4d07.firebasestorage.app',
    iosBundleId: 'com.company.opet.order',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkjSb7FXrFrtUsAW8mpXIVtX6f3sQ8Jqk',
    appId: '1:984481107482:web:23e518e3e14331f0a44ba3',
    messagingSenderId: '984481107482',
    projectId: 'food-order-f4d07',
    authDomain: 'food-order-f4d07.firebaseapp.com',
    storageBucket: 'food-order-f4d07.firebasestorage.app',
    measurementId: 'G-F2WGL6RKWQ',
  );

}